### PR TITLE
added queries for 5 module hvs

### PR DESCRIPTION
**Pull request by st0ne-dot-at**
Hi,
First of all. Thank you for you code. I appreciate it a lot.
I own a HVS Box with 5 modules. I've extendet the code to support 5 modules.
Regards,
Rob

### CODE REVIEW

**Comment by st0ne-dot-at** [comment]
I've you wish, i can send you the output of example.py in debug mode. So you see the responses in hex as well.

**Review by bbr111 — APPROVED** [review]
looks good.
If there is someone who has more than one tower, maybe we change thange the code to support that too.

**Comment by st0ne-dot-at** [comment]
i have 2 towers! I would love to implement that.

**Comment by st0ne-dot-at** [comment]
I've tried to query the 2nd tower, but i wasn't successfull. Maybe i did something wrong.
myRequests[16] is the switchover to the 2nd tower. What are the nexst steps.
Where did you get the request messages from? Is that a trace from the be-connect app?
best regards,
Rob

**Comment by bbr111** [comment]
Hi, mostly i got the code from here:
(https://github.com/christianh17/ioBroker.bydhvs/blob/master/main.js)
and transformed it from javascript to python.
I tried to keep it near to this, so update would be easier.

**Comment by bbr111** [comment]
If updated the code in main branch. maybe you can check if it works.
for me, it works.

**Comment by st0ne-dot-at** [comment]
2tower


works good with 2 towers! Thx

**Comment by st0ne-dot-at** [comment]
works like a charm! thx

2tower

**Comment by st0ne-dot-at** [comment]
works like a charm! Thx

2nd-tower

**Comment by st0ne-dot-at** [comment]
The cell-voltage list of the 2nd tower has only 128 entries. Should be 160.

**Comment by st0ne-dot-at** [comment]
There is some code missing for module 5 in the section "Handle second tower"

**Comment by st0ne-dot-at** [comment]
no I'm on discord. But i can creat an account. As far as I know, the module count must be the same on each tower.

**Pull request merged**
